### ISSUE TITLE
Non-exported symbols aren't found in sandbox package.

### ISSUE THREAD

**Issue by MatthewRock** [MatthewRock/cl-sandbox#1]
Although after using sandbox:start we can use all the exported symbols from our previous environment, we can't use symbols that aren't exported - e.g. function we just defined.

**Comment by phoe** [comment]
Add an option which explicitly imports all internal symbols of the previous package.

For example, if we define a function in `CL-USER` but don't export it, just using `CL-USER` won't do. You'll want to `do-symbols` on all internal symbols of CL-USER and explicitly import them in the new temporary package.

**Comment by MatthewRock** [comment]
Implemented in [commit #5](https://github.com/MatthewRock/cl-sandbox/commit/8ebc168d0eb1bc2fe57eef19ecd86a04327c74ee)
